### ISSUE TITLE
Request: Add User to Multiple Domains 

### ISSUE THREAD

**Issue by a1d3s** [PowerDNS-Admin/PowerDNS-Admin#1092]
Hello i cant figure out , how to add a single user to multiple domains.
Now i have to click every domain an edit them an add the user.
this is maybe strange if i have 1 or more user who have to manage 6 or more domains.
the users comes from ldap

**Comment by KostasMparmparousis** [comment]
Hello there!
A PowerDNS Authoritative server already has a built-in mechanism called "Accounts". Accounts are essentially a way of grouping various Domains with one another . PowerDNS-Admin builds upon said feature by allowing Users to gain access to every Domain of an Account, when they are paired with that Account.

However, you might find that creating at least one Account of grouped Domains for every User in your DB might not be the best practice. An elegant solution suited to your case (since you already use the LDAP AP) would be to make use of the LDAP Autoprovisioning feature ("ADVANCE" settings section on the LDAP auth tab).

While adding records to the LDAP attribute of your choice, you are enabling a user to have access to multiple Domains and/or Accounts. More information can be found [here](https://github.com/gunet/PowerDNS-Admin/wiki/Configure-PDA-user-privileges-based-On-LDAP,-OIDC-or-SAML-Attributes) .

**Comment by a1d3s** [comment]
Sorry , can't follow your answer, I don't understand what to do. What should be URN? UPN? 

We didnt use autoprovision.
I have Admin User which are used only as fallback for operators. All my users are operator if they work internal. And the user is used for external accounts. I have a hough amount of domains and customer. Some of them have more then one domain and maybe more then one user who should have access to these domains. I think it would be easier to add domains to a user then the user to the domain.

**Comment by a1d3s** [comment]
Ok after playing around with a second docker i thinki found the solution
Create Account (which mean Group users)
Assign the account to the domains i need , if i had a new user i can add them to these account insteed to add them to the domains.
