### ISSUE TITLE
The API key cannot be associated with a domain or account

### ISSUE THREAD

**Issue by glomazdov** [PowerDNS-Admin/PowerDNS-Admin#1140]
In previous versions, when creating an API, it was possible to bind domains to it.
This option is not available now ?

I made the binding via PG manually.
afte test:
I have created two APIs for two domains. But I can still create records in any domain using the API, even where I don't have access. How can I differentiate this and hard-link the API to a domain or a account? I think this is because the "user" role is needed for the key.

**Comment by jbe-dw** [comment]
Hello,
In the latest versions, API Keys behaviour has been changed:
- An API Key with the Administrator or Operator role can manage any domain registered in PDA
- An API Key with the User role can be bound to any domain or account. Given that an API Key bound to an account is able to manage domains owned by the account, adding such domains is silently ignored (ie they won't be added as they are managed with the account)
- API Keys with the User role should not be able to manage domains they don't have access to.
- In the edition screen, selecting Administrator (default) or Operator role hides account/domain association settings (and silently removes the former associations upon update).

In fact, if you're not able to assign a domain or an account is because the keys don't have the User role. You must select this role first, then add domains or accounts. All settings are listed in the API Key list screen.
