### ISSUE TITLE
How to rollover DNSSEC Key (KSK & ZSK) without failed ?

### ISSUE THREAD

**Issue by trinv** [PowerDNS-Admin/PowerDNS-Admin#1155]
Hi,
How can i rollover DNSSEC Key (KSK & ZSK) without failed ?
I want to changed the DNSSEC key for zones and can set some information for the DNSSEC Keys: settime, alg, length,....
Thanks

**Comment by jbe-dw** [comment]
Hello @trinv,

Can you elaborate your question ? I'm not sure to understand what you really ask ? Is it a question about DNSSEC or about how to do it in PowerDNS Admin ?

Regards

**Comment by arbaldin** [comment]
Hi @jbe-dw,

As far I understand @trinv question, it's related to PowerDNS-Admin.

I believe this is a PR, because I'm not sure if PDNS-Admin do the DNSKEY rollover.

When we enable the DNSSEC on a zone, I believe PDNS-Admin uses PDNS API to generate a DNSSEC Key and kepp in on the PDNS proper DB table. When I disable a DNSSEC from a zone, it looks disabled, but I'm not sure if it delete the DNSKEY from the PDNS DB. When we activate the DNSSEC again for the same zone, I see the key PDNS-Admin uses is the same as before.

I don't see any way through PDNS-Admin to generate a second key to change the previous one, so we could rollover from one key to another, keeping both for a time, an then deleting the first. I think this is what @trinv is considering.

Regards

**Comment by jbe-dw** [comment]
Thanks. I confirm PDA is not able to do the rollover. You have to use pdnsutil tool on the PDNS server directly following the directions [here](https://doc.powerdns.com/authoritative/guides/index.html).

**Comment by jbe-dw** [comment]
Hello @trinv,

As it is not supported now, I'm adding it to the long list of feature requests, and closing your issue now.

Regards

**Comment by jbe-dw** [comment]
Hello @trinv,

As it is not supported now, I'm adding it to the long list of feature requests, and closing your issue now.

Regards
