### ISSUE TITLE
Bash Script Auto Installer

### ISSUE THREAD

**Issue by alsyundawy** [PowerDNS-Admin/PowerDNS-Admin#1190]
hallo

thx for nice project, but can i req script auto installer on linux system with or without docker ?

**Comment by jbe-dw** [comment]
Hello,

You have some sample docker-compose scripts to startup with. We don't have a bash script but you can easily make one from the [docker build files](https://github.com/PowerDNS-Admin/PowerDNS-Admin/tree/master/docker).

We have not discussed about easier ways to deploy yet. I note it for later.

Regards

**Comment by alsyundawy** [comment]
i have successfully  install without docker on debian 11, its posible make script base on my history ?

**Comment by Metrax** [comment]
My personal opinion on this: I think such a script should not be added to the code, due to a lot of different setups, f.e. different distributions, different database setups, aso. If you put this script to the code, you have to add options for a lot of different setups and maintain it, which results in a lot of work. I think such a script would have a good place in the wiki, with an exactly description of the setup.

**Comment by AzorianSolutions** [comment]
@Metrax while I generally agree with your point of view on this, I however want to contest about the claim of complications. I think a basic installer that assumes very little about the environment other than being of Linux descent, would be reasonably easy to put together a less fault-tolerant script to at least speed up initial environment setup.

For instance, I could whip up a script that will run the basic commands for APT / YUM package installation, execute follow-up installation commands (such as npm and pip), and then print out the basic instructions (tailored to that deployment), for running the app.

**Comment by alsyundawy** [comment]
Cant wait 💅

**Comment by AzorianMatt** [comment]
@alsyundawy this will be provided in the next-gen app of PDA but not the legacy edition likely.
