### ISSUE TITLE
Is there an API?

### ISSUE THREAD

**Issue by Kraeutergarten** [PowerDNS-Admin/PowerDNS-Admin#127]
Hey,
is there an API for editing Zones? (For Let's encrypt for example)

**Comment by jallakim** [comment]
That would be inception-API, as PowerDNS-Admin utilizes the PowerDNS API. PowerDNS-Admin doesn't store any records of any kind in it's own database, and fetches/pushes records/whatnot from the PowerDNS API itself.

Therefore; use the PowerDNS API itself for things like Let's Encrypt. E.g. [pdns_api.sh](https://github.com/silkeh/pdns_api.sh) should do the trick (it's made to work with [letsencrypt.sh](https://github.com/lukas2511/letsencrypt.sh)).

**Comment by jallakim** [comment]
Adding users? LDAP-users can log in right away (but won't be able to edit any zones until an admin adds a user to a zone/multiple zones). You want an API to edit these permissions?

**Comment by jallakim** [comment]
The only thing I can see an advantage of PDA (PowerDNS-Admin) having it's own API, would be to "circumvent" the limitation in the pdns-API with only having one single API-key with full access (i.e. no role-based access control to define specific rights to specific zones).

**Comment by pschiffe** [comment]
@jallakim current workflow: add user to ldap, user logs in to pda, add user to domain. Even when user exists in LDAP, you can't just allow him to manage zone without him being in the pda db.

But again, I think that better solution to this problem is to let users to create zones. So admin doesn't need to. Ofc, this should be configurable.

**Comment by ivanfilippov** [comment]
If #130 is implemented with a per-user flag that allows users to create domains only if they're flagged (which is the right way, IMO), then your workflow would still be the same, you'd need a user to log in once, then enable them for domain creation after that.

I think #130 (and the use-case @pschiffe describes) could be solved by a new Role type, something like 'Power Users', which can create domains but can't modify other users or see server settings. There could be a config flag that decides if new users are Standard or Power Users by default and Admins could still change user roles as needed via the UI.

**Comment by pschiffe** [comment]
@ivanfilippov power users is good idea, but if that's too much work to implement, config flag if all users can create zones or not should be sufficient. With less functionality, but sufficient.

**Comment by Nosxxx** [comment]
My main problem is, that i need a "role based" API like @jallakim already described.

**Comment by kaechele** [comment]
@Nosxxx A role based API is something that could be achieved by using nginx as a proxy letting it handle authentication instead of pdns. Then you could use regexes to limit API access based on user/group and URL (endpoint) passed to the proxy.

**Comment by madpsy** [comment]
@kaechele Can you hand off authentication to somewhere else just now? If so, I'm interested how as that would be really useful for me too.

**Comment by tmuncks** [comment]
This would be rather useful IMHO, but for my use, I'd need to have it handled through PowerDNS-Admin, to ensure proper authentication and access controls.
Perhaps there's already an API specification that would be relatively easy to "drop in" as just another Flask route?

**Comment by icb-** [comment]
Shouldn't be too hard to mediate access to the relevant parts of the PowerDNS API itself. You could use the `X-API-Key` header with `<username>:<password>` for internal or LDAP accounts, either straight or base64 encoded [RFC2617](https://tools.ietf.org/html/rfc2617)-style. Or you could store an API access token for all user types (internal, LDAP, SAML, etc.)

[powerdns-auth-proxy](https://github.com/catalyst/powerdns-auth-proxy) is pretty close to what I'm thinking, but baked into PowerDNS-Admin instead of standalone. Reusing the PowerDNS API has a number of benefits. The most obvious that client libraries already exist for it, and is supported by Let's Encrypt clients (as the original request wanted) like [LEGO](https://github.com/xenolf/lego/tree/master/providers/dns/pdns).

**Comment by terbolous** [comment]
Letsencrypt supports rfc2136, which is also supported by powerdns. What's necessary is a method of creating TSIG keys

**Comment by mastacheata** [comment]
Currently you can only create TSIG Keys by using either pdnsutil or by querying the database of PDNS.
In PDNS 4.2.0 there will be a new API for managing TSIG Keys. As PDNS Admin is only using the API to manage PDNS, this might be worth looking into in a couple of months.

PDNS-Admin already exposes the metadata API via it's own API, but not in the UI (yet), so I'm not sure about the priority for adding that unless anyone steps up to submit a PR for those things.

**Comment by Daniel15** [comment]
I think this can be closed now as I think there is an API of some sort (https://github.com/ngoduykhanh/PowerDNS-Admin/blob/master/docs/API.md).

**Comment by github-sys-admin** [comment]
yeah what the hell is it
