### ISSUE TITLE
Remove mysqlclient from requirements.txt

### ISSUE THREAD

**Issue by dmcken** [PowerDNS-Admin/PowerDNS-Admin#1305]
The following is listed in the main requirements.txt file:
mysqlclient==2.0.1

Which ties all installations to MySQL, this should be removed to make the project more database agnostic.

**Comment by AzorianSolutions** [comment]
This is a great point. I would say if we want to execute a PR, it should include appropriate documentation updates to the current deployment documentation so that this oversight doesn't create further deployment issues. I think inserting the requirement in the current documentation at the right place would be a sufficient change to accompany the removal from the requirements.txt file.

**Comment by dmcken** [comment]
You can see the updates to the documentation in https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1302 not going to say I've gotten all of it out but the database dependencies are being moved out to the database setup guides.

**Comment by AzorianSolutions** [comment]
@dmcken This looks good.

Would you mind addressing this minor issue in the MySQL DB setup documentation? If you need help with the command I can provide but I imagine you already know Yum.

![Screenshot from 2022-12-09 09-37-32](https://user-images.githubusercontent.com/65595341/206726252-a79e55db-0a1d-4090-9060-591d509ede48.png)

**Comment by dmcken** [comment]
PR #1310 should resolve that.
