### ISSUE TITLE
Enhancement: better RECORDS_ALLOW_EDIT

### ISSUE THREAD

**Issue by pschiffe** [PowerDNS-Admin/PowerDNS-Admin#131]
Currently, RECORDS_ALLOW_EDIT config option results in an unexpected behaviour. If record type is missing in RECORDS_ALLOW_EDIT, nobody is allowed to see that record, and nobody is allowed to edit that record. If the record is included in RECORDS_ALLOW_EDIT, everyone can see and edit that kind of record. I'm suggesting this behaviour:
- everyone can see any kind of dns record  any time
- admin can edit any kind of dns record any time
- user can edit only record types specified in RECORDS_ALLOW_EDIT

I think this makes much more sense, and with #54 implemented, pdns admin would be near perfect project. Example, admin prepares template for domains with SOA and NS records pre-filled. User can edit any record type except SOA and NS. Sweet, right? Inspiration from the wild: Google Cloud DNS works very similarly to what I just described.

**Comment by bergzand** [comment]
I'm currently working on this.
The interface side is rather easy to modify to allow this, but server side checks would have to be done to verify whether forbidden records are modified

**Comment by vmarkop** [comment]
Hello,

This request is stale for too long. Since then, PRs like #1113 aim to improve record permissions. Regarding our policy to clean up this project, we're closing it. Feel free to open a new issue later.

Regards
PowerDNS Admin Team
See https://github.com/PowerDNS-Admin/PowerDNS-Admin/issues/1153 for the policy
