### ISSUE TITLE
Issue with auto adding domain suffix

### ISSUE THREAD

**Issue by ichisuke55** [PowerDNS-Admin/PowerDNS-Admin#1321]
Hello, maintainers.
I think https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1300 change will add a subdomain suffix to the already registered records, is this correct?  
Could you look at the following as a reference?

1. I found this issue with [ngoduykhanh/powerdns-admin:latest](https://hub.docker.com/r/ngoduykhanh/powerdns-admin/tags)
2. [powerdnsadmin/pda-legacy:v0.3.0](https://hub.docker.com/r/powerdnsadmin/pda-legacy/tags) is not realize this situation
- Before (zone name is test1-sys12.com)
  - abc.test1-sys12.com / A / Active / 60 / 10.164.1.10
    - This is already registeed record.
![Screen Shot 2022-12-12 at 15 11 15](https://user-images.githubusercontent.com/60389350/206975532-792fed0b-35b7-4370-97e2-9f8909b0059c.png)
- After Apply Changes at UI button
  - abc.test1-sys12.com.test1-sys12.com / A / Active / 60 / 10.164.1.10
    - test1-sys12.com suffix auto added and backend SQlite3 record also tha same record.
![Screen Shot 2022-12-12 at 15 11 28](https://user-images.githubusercontent.com/60389350/206975542-75843476-156f-450d-9dfe-37b515d9b323.png)

**Comment by nickmaleao** [comment]
I'm having the same issue, every time I make a change and apply the settings, the domain is incremented in the dns record.

I will stop making changes for now.

**Comment by domXmob** [comment]
looks like this was the source of the issue:

https://github.com/domXmob/PowerDNS-Admin/commit/52169f698c783e9e057b0be9df2cc0cdb47e72b5

**Comment by AzorianSolutions** [comment]
@ichisuke55 @domXmob The PR with the rollback has been merged.

**Comment by ichisuke55** [comment]
@AzorianSolutions 
Thank you for your quick fix!

**Comment by AzorianSolutions** [comment]
@ichisuke55 You're welcome! My apologies for the quick break to go with it!

**Comment by zivillian** [comment]
are there any plans to push a new docker image?

**Comment by AzorianSolutions** [comment]
@zivillian yes, there will be multiple images made available for the next-gen application. The current generation app may also get a good update in that department depending on time and resources.

**Comment by seitzbg** [comment]
This is still broken in Docker and makes the app unusable...

**Comment by AzorianMatt** [comment]
@seitzbg let's start with you telling us exactly what image you're using (full repository path and tag).

**Comment by seitzbg** [comment]
I was using https://hub.docker.com/r/ngoduykhanh/powerdns-admin before and had no idea there was a new image path.  Is that something communicated on a mailing list or such?

**Comment by seitzbg** [comment]
I was not aware there was a new maintainer and now understand the reasoning behind the current state of affairs.  Thanks for your time and effort, I appreciate it.

**Comment by AzorianMatt** [comment]
@seitzbg thank you as well for taking the time to understand and appreciate the situation.

I'm doing what I can to recover the project and get it back on track to aggressive forward movement. That challenge however does not come without plenty of scenarios that will rub users wrong and cause some headaches. It's just the unfortunate status quo of where things are.

If you spend some time looking through the repository, you will see that our efforts have really picked up since I took over so we will get there. I could of course handle things differently at times, but I come from a past where sugar coating has only enabled bad habits and lack of personal development so I stand behind my aggressive nature as a method of resolution.

I recommend you get switched over to the new image as I'm sure you will find some of the updates pleasant. That's not to say that it doesn't come without some new issues as well, but we are working aggressively to get those cleaned up and another patch release out very quickly.

**Comment by seitzbg** [comment]
I fully understand your response!  I had the wrong attitude coming here with my issue as I was just frustrated to have to fix my DNS records in mysql again by hand.  

I am currently using the new image path.  I would also not mind testing the dev branch to provide feedback.  Is it in a state where that would be viable or still mostly a work in progress?

Again, I really appreciate the effort on this project especially since it only exists due to the effort from people like you.

**Comment by AzorianMatt** [comment]
@seitzbg I truly and greatly appreciate that sentiment and transparency! I too have done the same thing so I'm not innocent either. I know it's frustrating to say the least, especially if it's for production.

To answer your question, the dev branch currently is pretty darn close to the 0.4.0 release and should have the same stability of that release at this time. Of course, that is always subject to change, but we do try to keep from pushing outright breaking changes intentionally since it can mess with all of our efforts on maintenance.

I will say this though, be mindful of using the dev release in production because I will often merge PRs without the greatest testing, if any sometimes. That could result in a situation that breaks your production if you are doing automatic image updates of any sort.

**Comment by seitzbg** [comment]
Yep appreciate the heads up.  It is production but not super important production (my house ;)).

**Comment by patvdleer** [comment]
switching to `powerdnsadmin/pda-legacy:latest` fixed the issue, I completely missed the change in docker images, maybe put up a big ass notice on the README?
