### ISSUE TITLE
Add support for `ARM64` based Docker images

### ISSUE THREAD

**Issue by grzegor** [PowerDNS-Admin/PowerDNS-Admin#1505]
### PDA version

0.4.0

### Feature type

New functionality

### Proposed functionality

Would it be possible to update the docker image building stack to also make arm64 (aarch64) images for dockerhub and/or github container repo? Just tested it and it builds and works fine without any modifications to the current Dockerfile. Docker buildx automatically picked ARM Alpine base and the rest is pretty much architecture agnostic anyway.

### Use case

Ampere servers gets more and more common, AWS have their Graviton on EC2, many people uses M1 Macs as a budget low power servers and there's of course the plethora of home labs on RPi and more powerful rockchip based alternatives — all would benefit from an official docker image without the need of relying on untrusted and usually very outdated homebrew images currently available on dockerhub.

### Database changes

None

### External dependencies

None

**Comment by AzorianMatt** [comment]
@grzegor This has been completed and added for the `0.4.1` release of PDA. Please try your deployment again against the appropriate image tag and let me know if all works as expected.

Thanks!

**Comment by grzegor** [comment]
@AzorianMatt I tested the image on my M1 MBP dev machine via [Colima](https://github.com/abiosoft/colima) and also on a RK3399 based dev board - both works flawlessly.

Not sure if that's intentional for testing purposes, but the arm64 image is only tagged as `master` on dockerhub (and the other one is `dev` but I didn't test that on yet), only the amd64 image is tagged `latest` and `v0.4.1`.

I see on github workflow that QEMU added ~16 minutes to the image build process in comparison to amd64 only from last month. I hope that's not a problem taking the infrequent release schedule into account?

**Comment by AzorianMatt** [comment]
@grzegor the tagging is probably weird because of how the image building is done and how I pushed this change in. I think it showed up under the `master` tag because I ran a manual execution of the workflow to test the change. I would have though this would have re-ran when I updated the `0.4.1` the day after the initial release. I'll take a look and see what I can do to correct that.

As for the time it added, I'm hoping we can make it more efficient in the future or at least break the build jobs into separate executions so that the primary image (`AMD64`) isn't delayed in it's build process. Given that releases are infrequent right now, this isn't a big deal but it will become more of an issue once the project goes more agile in the future. We will get it figured out though!

**Comment by grzegor** [comment]
Sure, I'll take a look after the weekend. I'm not really skilled in github actions, but I'll try to dig into what could have caused it. 

There are also rumors that Microsoft will share some of their ARM64 Azure machines to build against natively in GH actions so the build time problem should not be an issue in the future.

**Comment by AzorianMatt** [comment]
@grzegor after further review, I'm thinking the reason why it didn't make it to the tagged release is because I originally forgot to include the additional platform in the last build step which tags the release.

If that's true, that means the build should be available in the next release that I intend to do in the coming weeks.

**Comment by grzegor** [comment]
Oh yeah, that's probably the reason.

**Comment by AzorianMatt** [comment]
@grzegor the final version build of this edition of PDA should be coming in within a matter of weeks so you can finally expect to see this in there. Thanks!
