### ISSUE TITLE
Every time after apply changes on some domain, pdns admin attached domain name to existing record name. 

### ISSUE THREAD

**Issue by sjajni** [PowerDNS-Admin/PowerDNS-Admin#1510]
### PDA version

0.4.0

### Python version

3.0

### Steps to Reproduce

1, change some record in domain,
2, click save,
3, click Apply Changes

### Expected Behavior

Changes are preserved without changes on other records

### Observed Behavior

When you click Apply changes powerdns admin every time add domain name to record name for example

host.domain.com
 becomes 
host.domain.com.domain.com
 And such change is applied to all records in domain.
After every apply he add additional domain.com,
so host.domain.com.domain.com becomes host.domain.com.domain.com.domain.com and so one.

I use latest docker image ngoduykhanh/powerdns-admin:latest

**Comment by AzorianMatt** [comment]
@subbink you can't reproduce this because this person isn't using the official project image but instead a very outdated copy.

@sjajni I'm rejecting this report because it is one of many duplicates that violates the contribution guidelines of the project. Furthermore, you need to read through the project documents and use the appropriate Docker image or source. You do not have version 0.4.0.

**Comment by sjajni** [comment]
Thank you a lot and sorry I bother you.
I installed powerdnsadmin/pda-legacy:latest and everything works fine
Thanks again.
Best regrds
