### ISSUE TITLE
Password appears to be cleared when saving profile

### ISSUE THREAD

**Issue by whitepiratebaku** [PowerDNS-Admin/PowerDNS-Admin#1568]
### PDA version

0.4.0

### Python version

3.0

### Steps to Reproduce

1. login as normal local user
2. go to profile
3. hit save profile
4. logout
5. when you try login you see password not works

### Expected Behavior

save profile should does nothing and password should not be cleared out

Note: reason I was hitting save profile without doing any changes because I was enabling OTP and as soon as you enable OTP tab switches to "Personal Info" and I thought that I have to hit save profile which in return cleared the password, later on when I was trying to login it was failing and I was thinking it is otp causes issues.

### Observed Behavior

user password cleared

**Comment by mrimann** [comment]
@AzorianMatt FYI: I just had a customer with a fresh account complaining about login issues after an initially working login. We then tested it together and found exactly the same issue described here. Or in other words: I can confirm the issue with v0.4.1

The steps we've done were:
- Login (user + pass, no MFA)
- go to the Profile page
- click "Authentication" to switch to that "Tab"
- set the checkmark at "Enable 2FA"
- instead of the QR code, the "Profile" Tab with the username/email is shown
- user clicked on "Save profile"
- logged out

From here on, user was not able to log in again, neither with user/pass/token, nor with user/pass after I as an admin disable 2FA for this account again.

Logging in became possible again after I reset this user's password.

What works and did not cause unwanted side effects is logging in -> Profile -> Change Password tab and there just change the password and hit "Save Password" below the two form fields.

Hope this helps to narrow down the issue + solve it.

**Comment by chvogel** [comment]
I have the same issue with the new DNS management solution that our IT partner set up (PowerDNS v0.4.1).

Saving in either the profile tab (with no changes) or the password tab (with both password fields empty) somehow overwrites/clears the password and makes it impossible to log in.

It is possible to recover by changing the password again (if you are still logged in to that account).

(Verified this issue by trying to log in in a separate browser session after saving and after "changing" the password back.)


I discovered this issue exactly the way @mrimann described for his client.
(I enabled 2FA and then hit save in the profile, reasoning that enabling 2FA should require more than just clicking a checkbox once.)

**Comment by AzorianMatt** [comment]
@mrimann @chvogel thank you for confirming this.

**Comment by Aleksanaa** [comment]
Can confirm this... Just modified the email address of admin(first account), and got locked out. So I clicked F12>Network, right clicked on the login POST, "edit and resend", and removed password from the Body (edited to password=), and logined successfully. Just in case anyone gets troubled by this stupid bug...

**Comment by AzorianMatt** [comment]
> by this stupid bug...

Care to elaborate on this or do you just want to dog on the efforts of the many from the long history of this project?

**Comment by mrimann** [comment]
@AzorianMatt As you closed this issue, I expected it to be resolved in v0.4.2 and waited until today when I updated our PowerDNS-Admin Setup. I can still reproduce the issue exactly as described here. Maybe worth looking into a fix for this accidental password-overwriting issue before releasing v0.4.3?

**Comment by AzorianMatt** [comment]
@mrimann are you not reading the project update announcements at all?

**Comment by mrimann** [comment]
@AzorianMatt I've looked at the release page https://github.com/PowerDNS-Admin/PowerDNS-Admin/releases/tag/v0.4.2 but that seems not to contain what you're referring to...? What exactly did I miss?

**Comment by chvogel** [comment]
@AzorianMatt
I for one am only subscribed to updates to this specific issue, so I didn't get any pointers regarding the announcement.
The 0.4.2 release notes do mention a "freeze release", but there's no link to the actual announcement with all the important details.

But regardless of how visible the announcement is, I think the main misunderstanding comes from you closing this issue "as completed" without any additional information. This usually indicates that an issue was actually fixed in the latest release.

If you're mass-closing issues that won't be addressed before the freeze and that will be obsolete after, I would suggest either closing them with a different state than "completed" or at least adding a tag indicating this, like "obsolete / release-freeze".

**Comment by AzorianMatt** [comment]
@chvogel you'll have to take that up with Github. They really should have provided a better mass close tool than what we currently have. Sure, I could add a tag to that. But that's not universal and I would end up right back in this conversation with the next person that doesn't agree with the tag approach.

It's unfortunate, but I wasn't going to write a script or spend a lot of time manually closing hundreds of issues, on a project that I plastered with freeze notifications, announcements of that, and announcements before that instructing people to continue following announcements.

There really is no winning to this problem. You will all have your own individual expectations of how it should be handled, and if it doesn't align, it's not good enough.

**Comment by AgentTNT** [comment]
I know this is a very late reply, however this was just patched - https://github.com/PowerDNS-Admin/PowerDNS-Admin/pull/1879 and called out in the v0.6.1 release notes. Trying to backtrack through the closed issues overall that are still valid, as well as time permits!
