### ISSUE TITLE
HTTP 500 Error when managing domains

### ISSUE THREAD

**Issue by DaemonHunter08** [PowerDNS-Admin/PowerDNS-Admin#1589]
### PDA version

0.4.1

### Python version

3.9

### Steps to Reproduce

1. Install Rocky Linux 9.2
2. Install Powerdns
3. Connect Powerdns to existing database backend
4. Install Powerdns-Admin 0.4.1 by following this guid "https://computingforgeeks.com/configure-powerdns-on-rocky-linux/"

### Expected Behavior

Expecting to manage domains like the older version.

![image](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/136132004/1d9bc4ec-dd88-4430-9135-91d53bd0203f)

### Observed Behavior

when trying to manage domain by clicking it, it show's "It show's "HTTP 500 Error"

![image](https://github.com/PowerDNS-Admin/PowerDNS-Admin/assets/136132004/2c317b69-76e0-44d3-a330-b60752fe705f)

**Comment by AzorianMatt** [comment]
@DaemonHunter08 why did you file this as a bug? YOu used a random third-party article that is outdated to do the deployment?

Pro tip, articles that directly copy the database schema into them instead of referencing an official source of truth, our recipe for this disaster.

Please use the project's official deployment guides as that is the only thing we will try to offer some support on.

Bug report denied.
