### ISSUE TITLE
Fresh Installation, Create Zone HTTP 400

### ISSUE THREAD

**Issue by clarence-simplex** [PowerDNS-Admin/PowerDNS-Admin#1606]
### PDA version

0.4.1

### Python version

3.11

### Steps to Reproduce

Click side menu  Create Zone
Enter Zone Name, e.g. test.com
Click on Primary button
Click on button Create Zone and resulted HTTP 400 Error

Browser console shows:  POST http://127.0.0.1/domain/add 400 (BAD REQUEST)

### Expected Behavior

A new zone should be created and verified using pdnsutil list-all-zones, but none was created.
Creating zone using pdnsutil command is fine.

### Observed Behavior

Setup was done using git clone https://github.com/ngoduykhanh/PowerDNS-Admin.git
Installation has no error and PowerDNS-Admin accessible via http://127.0.0.1

Installation environment
OS: Debian Bookworm
Python: 3.11.2
NodeJS: 18.16.1

**Comment by AzorianMatt** [comment]
@clarence-simplex I'm denying this bug report as you have not provided nearly enough information to call this a bug. We have no clear example of your environment configuration, log outputs, or anything to support a reasoning other than improper deployment.

Given that you referenced a very outdated repository URL, it does leave me concerned that you also followed some sort of third-party guide that is severely outdated.

**Comment by clarence-simplex** [comment]
I run the docker version, still get the same error in zone creation.
Where can I get the details for the so called improper deployment?

**Comment by AzorianMatt** [comment]
@clarence-simplex I take it by your response that you did not care for my assertion of an improper deployment until proven otherwise, hence your use of quotes.

Perhaps you should have tried starting a discussion about your deployment to get to the bottom of your issue before just turning it into an assumed bug (which it might be). The issue here is that you didn't do your diligence and just offloaded it onto the project members while not even providing enough detail for someone else to do your job for you. Ignorance is no excuse here, you have access to search engines the same as I do.

Given that this project is in the business of free help, I think you're more than welcome at this point to go find it elsewhere.

**Comment by clarence-simplex** [comment]
I did. For the past week, I've attempted to install PowerDNS-Admin on Debian bookworm for uncountable times, retried on Bullseye again and finally using a docker as recommended and experienced the same outcome. 
Perhaps my assumption that it could be a bug is abrupt and written responses often mis-interpreted. 
Thanks Matt, I appreciated the prompt responses.

**Comment by stevenmunro** [comment]
this stinks
