### ISSUE TITLE
MySQL InnoDB Cluster Error for domain_apikey table

### ISSUE THREAD

**Issue by Scraps23** [PowerDNS-Admin/PowerDNS-Admin#1636]
### PDA version

0.4.1

### Python version

3.10

### Steps to Reproduce

1. Initialize a MySQL InnoDB Cluster
2. Install PowerDNS admin pointed at the cluster (in my case, I use mysql-router to LB the cluster)
3. Reboot the mysql instance

### Expected Behavior

The MySQL instance should boot without issue and rejoin the cluster as long as one cluster-member stays live

### Observed Behavior

The server worked as expected for a while, but the cluster members failed to rejoin on reboot.

While trying to reinitialize the cluster, the following error was encountered in mysql-shell:
```
ERROR:The following tables do not have a Primary Key or equivalent column:
powerdnsadmin_operations.domain_apikey

Group Replication requires tables to use InnoDB and have a PRIMARY KEY or PRIMARY KEY Equivalent (non-null unique key). Tables that do not follow these requirements will be readable but not updateable when used with Group Replication. If your applications make updates (INSERT, UPDATE or DELETE) to these tables, ensure they use the InnoDB storage engine and have a PRIMARY KEY or PRIMARY KEY Equivalent.
If you can't change the tables structure to include an extra visible key to be used as PRIMARY KEY, you can make use of the INVISIBLE COLUMN feature available since 8.0.23: https://dev.mysql.com/doc/refman/8.0/en/invisible-columns.html

ERROR: Instance must be configured and validated with dba.check_instance_configuration() and dba.configure_instance() before it can be used in an InnoDB cluster.
ERROR: RuntimeError: Instance check failed
```

Adding a primary key to the `domain_apikey` table allowed the system to re-enter the cluster.

**Comment by AzorianMatt** [comment]
@Scraps23 this should not have been reported as a bug. The project states nowhere that it currently supports clustered deployment. It's unfortunate that this is the case, but reporting it as a bug because it doesn't fit your scenario is not an appropriate reaction.

**Comment by Scraps23** [comment]
The documentation explicitly states [support for MySQL and MariaDB](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/docs/wiki/database-setup/Setup-MySQL-or-MariaDB.md), and Clustering is a native feature to both of those.
This is reported as a bug as this software currently causes infrastructure-breaking behavior; submitting a bug report is an entirely appropriate response, especially when the fix involves adding a primary key to a single table.

At the very least, this needs to be added to the list of [known issues for MySQL deployments](https://github.com/PowerDNS-Admin/PowerDNS-Admin/blob/master/docs/wiki/database-setup/Setup-MySQL-or-MariaDB.md#known-issues).

**Comment by AzorianMatt** [comment]
@Scraps23 many pieces of software have lots of features, that doesn't mean this project can make consideration to every single one of them. I really don't care for this view. You make assertions like this project is loaded with resources to get things done. LOOK AROUND. Does it look like this project is doing so well that we can go as far as testing MySQL clustering when we can't even get third-party auth mechanisms stable? Hell, we can't even get security holes eliminated due to the dependency nightmare alone.

If you aren't already, you should join the project Discord and take a look at the conversation taking place (literally at this moment) in the #general channel. I think it would do you some good to understand the can you just opened with that assertion.

After you hop in there and read the conversation from today, maybe you can get started on a PR to update the list of known issues if you feel it's important. The reality you seem to fail to recognize, is that this would have been made a priority if you weren't the first person to raise the issue. It just hasn't been a major issue with the core audience based on current feedback. Auth mechanisms however, have caused huge amounts of feedback due to issues (as an example).

**Comment by AzorianMatt** [comment]
@Scraps23 

> This is a really disappointing display of pride. Good luck with your project.

Pride? There's not a lot of pride to be taken with the level of disaster that is present currently. Instead,

I get to spend some amount of the little time I have, informing certain community members of their lack of awareness to their own entitlement. Hence this interaction as an example.

Just like so many others that have interacted with this project, you seem to have come up with your own arbitrary reasons why your particular need deserves an exception to the consideration. It never seems to matter about the bigger picture or the other very relevant struggles that the project has.

Case and point. You argued that this was important because it directly impacts infrastructure irregardless of the fact that you're the first person I've even seen bring this up.

Everyone is just out to get theirs.

**Comment by Scraps23** [comment]
With the way you moderate, I'm not surprised you can't get the necessary help.

You assumed I'm pushing for a fix because I need it personally, but my deployment script handles all of that for me. Out of courtesy, I provided you details of a problem and its fix that you didn't know about.

You chose to react... this way.

**Comment by AzorianMatt** [comment]
@Scraps23 you're the epiphany of what plagued this project in terms of contributions. Everyone's got something to report, very few do anything about it other than writing up a vague issue, that often completely disregards the contribution guide.

You yourself pointed out that at minimal, a quick update to a single piece of documentation would be helpful. I still don't see a PR from you on that.

So please, go ahead and tell me about the reasons you think this project doesn't have good help. You literally just embodied it.

**Comment by Scraps23** [comment]
It's astounding you'd still expect someone to help you after treating them like this. You're one silly person.
Good luck with your disatrous project and fixing _whatever_ it is that could be causing that. _Certainly_ not childish outbursts when people try to improve it..

**Comment by AzorianMatt** [comment]
@Scraps23 if you think that's an outburst, it's just proof of why I should continue not wasting time or energy in trying to walk on eggshells around you overly sensitive, weak-minded people.

I don't want your help, I was just illustrating the point of how wrong your assertion is. Stand by for proof of what I think of your "help."

I understand, it sucks to hear that you're part of the problem, and not part of the solution.
