### ISSUE TITLE
Ldap (Active Directory) Auth failed Invalid credentials

### ISSUE THREAD

**Issue by nohnaimer** [PowerDNS-Admin/PowerDNS-Admin#1638]
### PDA version

0.4.1

### Python version

3.10.11

### Steps to Reproduce

1. Start PowerDNS Admin via docker-compose.yml
2. Configure Ldap Active Directory
3. Basic filter: (objectClass=organizationalPerson)
4. Groups created in Active Directory: Global/Security
5. Try login - get error:
```bash
[2023-08-03 18:41:21 +0000] [8] [ERROR] User 'user' does not belong to any group while LDAP_GROUP_SECURITY_ENABLED is ON
[2023-08-03 18:41:21,782] [user.py:305] ERROR - User 'user' does not belong to any group while LDAP_GROUP_SECURITY_ENABLED is ON
[2023-08-03 18:41:21 +0000] [8] [WARNING] User user failed to authenticate via LDAP from 10.165.18.26
[2023-08-03 18:41:21,783] [index.py:579] WARNING - User user failed to authenticate via LDAP from 10.165.18.26
```

### Expected Behavior

Success login via Active Directory

### Observed Behavior

Get Invalid credentials error

**Comment by AzorianMatt** [comment]
@nohnaimer this should not have been reported as a bug. Remain more humble and ask for help as a starting point. The LDAP auth feature currently works for a number of deployment scenarios, so while it might possibly not work for yours, it doesn't make it a bug. Furthermore, LDAP is complicated so I can only assume that you might have improperly configured PDA for your scenario.

**Comment by nohnaimer** [comment]
More modestly - it’s somehow strange. If you do not want to react to bugs, close the ability to create an issue. And thank you, I finally figured out what the problem is and if it’s not a bug, then what should I call it?

The behavior is exactly the same as described here - https://github.com/PowerDNS-Admin/PowerDNS-Admin/discussions/1525

I change into the database value of the ldap_sg_enabled parameter to False and everything worked.

Maybe someone will find this feature useful...

**Comment by AzorianMatt** [comment]
@nohnaimer of course we want to react to bugs, we want to react to everything. This simply isn't plausible with the current list of challenges in contract to the quality help that is available to contribute. It's unfortunate but this is the reality today.

As for your question, one could classify this as a `feature-update` on the basis that it is preferred to work differently for some scenarios. Being a user of LDAP, I would think you would recognize how hard this is to get right universally given that LDAP is very flexible in how organizations may use it. Granted, the original feature probably wasn't designed with the best insight to many differing environments, that doesn't make it broke since it does currently serve a number of environments without trouble.
