### ISSUE TITLE
Why is the docker container called 'legacy', where is the 'release'?

### ISSUE THREAD

**Issue by DaanSelen** [PowerDNS-Admin/PowerDNS-Admin#1696]
### Change Type

Correction

### Area

Installation/upgrade

### Proposed Changes

Please elaborate on this issue

**Comment by alm-nl** [comment]
The latest release can be obtained by using one of these:
docker pull powerdnsadmin/pda-legacy:latest
docker pull powerdnsadmin/pda-legacy:v0.4.1
docker pull powerdnsadmin/pda-legacy:0.4.1

It's called legacy because the developer is 'working' on a new project to replace PowerDNS-Admin. The latest release of pda-legacy is v0.4.1. I have asked on a update on the status of the projects, but so far it's quiet...

Hope this answers your questions.

**Comment by DaanSelen** [comment]
Thank you, it does.

**Comment by AzorianMatt** [comment]
@alm-nl The simple answer to this right now is that things are moving dreadfully slow. The community's constant demand of further updates and work on the legacy edition continue to drain the little resources there are. It's a total disaster and I'm about to freeze the legacy edition all together because it's becoming far too costly to project goals.
