### ISSUE TITLE
Remove includes of external sites

### ISSUE THREAD

**Issue by mathieumd** [PowerDNS-Admin/PowerDNS-Admin#174]
PowerDNS-Admin is bound to be used inside enterprises premises, managing very sensible data. It should not include any links to providers like `fonts.googleapis.com`, `cdnjs.cloudflare.com` or `gravatar.com`! All such data should be included into the sources, or if not possible (for Gravatar) enabled only _after_ confirmation by the user.

**Comment by lethargosapatheia** [comment]
DNS is part of core infrastructure. I can't believe this is the default, even after 4 years since the issue was opened! We have the exact same problem, we deal with real sensitive (not sensible) data. That we would give google hints about when we access our dns interface is outrageous, I'm sorry to say. This is a big confidentiality/trustworthiness problem.

**Comment by danimo** [comment]
`OFFLINE_MODE = True` removes requests to Google and Gravatar with no other disadvantages.

That being said, I dislike the wording (and the default), because it implies that contacting 3rd party services for fonts and pictures is at all desirable. HTTP/2 obsoletes the performance advantage, and traffic should be negligible for a DNS frontend. Also, images can be delivered as claims in a more data protection friendly manner when using e.g. OIDC.

My recommendation would be to:

1. Kill the code path that uses Google for fonts entirely
2. Support OIDC claims for pictures
3. Make Gravatar an optionally supported feature
4. Remove OFFLINE_MODE

If  @ngoduykhanh agrees, I would draft a PR for this. If not, I would draft one explaining offline mode in `README.md`.

**Comment by zoeller-freinet** [comment]
Hi @danimo,

given #1032, I'm inclined to say: please go ahead. With @RGanor and I, there are at least two maintainers now, so we should be able to make it happen.

**Comment by RGanor** [comment]
@danimo what you say make sense, but bare in mind that offline mode is not just for the reasons you mentioned above, some deployments are completely isolated from the internet, so relying on external service is not possible.
If any changes will be made, it still need to support such deployments.

**Comment by danimo** [comment]
I am aware of the offline modes intent, but with a privacy-by-default mode, the whole point is that there should no outside services left to contact in a default deployment.

**Comment by jbe-dw** [comment]
Hello @danimo 

I agree with you. We don't have resources to adress it right away but it should be done in a not too far future.

Regards
