### ISSUE TITLE
LDAP Authentication Errors

### ISSUE THREAD

**Issue by theAsylum-dk** [PowerDNS-Admin/PowerDNS-Admin#1754]
There seems to be a problem with the latest (0.4.2) docker image (as can be seen from the attached logs).

With :latest|0.4.2 authentication seems to work, but later lookups seem to go wrong.

After rolling back to 0.4.1 the errors seem slightly reduced - at least enough to allow login.

[pdns_ldap_err_0.4.2.txt](https://github.com/PowerDNS-Admin/PowerDNS-Admin/files/14258455/pdns_ldap_err_0.4.2.txt)
[pdns_ldap_ok_0.4.1.txt](https://github.com/PowerDNS-Admin/PowerDNS-Admin/files/14258459/pdns_ldap_ok_0.4.1.txt)

P.S.: Yes, I'm aware that the recent project changes maight mean that this won't be looked at (although I do hope that I'm wrong ;) ) - so this is also meant for any others to find and be aware of.

**Comment by AzorianMatt** [comment]
@theAsylum-dk ironically, the reason why I froze the project was to stop all activity that has to be managed including these issues. Obviously not a big deal for me to deal with an issue here and there, but that's really why I made it so hard to post the issue in the first place.

You can look through an extensive history of closed issues that are unresolved. The very nature of your problem is also the very reason for the freeze in the first place.
