### ISSUE TITLE
Recommendation Zones and recursor 

### ISSUE THREAD

**Issue by santxus** [PowerDNS-Admin/PowerDNS-Admin#264]
Hi guys

Again thanks for this proejct.

I would like to ask you about your recommendation with pdns + DNS-admin, Do you prefer master and slave or use mysql replication (I'm using mariadb)?

Second thing is how are you using recursor ? Maybe this question should no be here.

Im not pretty sure about the config in the new version.

Thank you!!

**Comment by tmuncks** [comment]
Probably not a universal answer, because circumstances differ. But native mode with mysql replication is awesome for a number of reasons:
* No need to maintain domain names in multiple places.
* Zones can be transferred securely with ssl
* Fast
* Zones stay in sync no matter what you do (even if for some reason the soa serial is screwed up) 

On the other hand, it's perhaps a bit more complicated to configure properly.

**Comment by tmuncks** [comment]
By the way, recursor has nothing to do with this. PowerDNS-Admin helps administer the authoritative end of the DNS chain.
