### ISSUE TITLE
lets encrypt and update UI

### ISSUE THREAD

**Issue by santxus** [PowerDNS-Admin/PowerDNS-Admin#410]
Hi Team

First thing thank you for this project is really nice. I have two questions:

Can we use this interface to renew automatically lets encrypt certificated in all domains ? I think that the process is connect to the ui create a txt record and delete it after the check.

Second is, how i can update PowerDNS-Admin if you releases a new version or new functionality? 

Thank you

**Comment by Oratorian** [comment]
Since this Container is Not Hosted as official docker on docker.io

You have to enter the direction where you downloaded the files.

Depending on how you downloaded 
You either need to type git pull
If you used the git clone command to download everything or if you downloaded manually you need to redownload as zip file and extract and overwrite all files.

After that a simple docker-compose build will do the trick and after a docker pull to redownload and update the psiw4rd/pdns-server from docker.

**Comment by santxus** [comment]
Thank you for your comment.

About the lets ecnrypt is someone managing auto renew ?

**Comment by Oratorian** [comment]
I am Running nginx and PowerDNS-Admin as a systemd Service. For le certification I use certbot which will install a crontab for auto renewal every 90 days

**Comment by santxus** [comment]
Thank you buddy !

I wll try that. In your opinion what is better mysql master master o axfr replication via SOA ?

**Comment by Oratorian** [comment]
I prefer afxr over Mysql master master, since both pens have their own database. Otherwise you can use mysql replication

**Comment by zoeller-freinet** [comment]
Renewing certificates shouldn't be a responsibility of PowerDNS-Admin.

**Comment by ngadiemin** [comment]
How to for solution this case, renew ssl certbot error module 'lib' has no attribute 'X509_get_notAfter'
