### ISSUE TITLE
NGINX or Apache Installation Instructions?

### ISSUE THREAD

**Issue by adam915** [PowerDNS-Admin/PowerDNS-Admin#623]
Can anyone shed some light on the steps it takes to get this working with NGINX or Apache on Ubuntu 18.04?

After spending 4-days beating my head against a wall trying to get this to work in CentOS 8, CentOS 7, Debian, and now Ubuntu 18.04 - I was finally able to take bits and pieces of instructions from a handful of different documents I was to get everything working with the Flask server on port 9191.  

At this point I have PowerDNS installed and working and have the server PowerDNS-Admin.service working too - but for the life of me can't get it to work through NGINX or Apache.

If someone can help - I would gladly share/document the steps I have taken so far to get things working so others can use it.

Thanks in advance...
-Adam

(to clarify - following the instructions listed on this site and the Wiki don't work...)

**Comment by sshipway** [comment]
I've managed to get it working with nginx.  There's a few steps.
* In the wiki is a good nginx config file you can use as a starting place
* If you have selinux you'll need to disable it or allow connecting to external sockets
* Create a user and group to own the process (I used pdnsa:pdnsa)
* Start powerdns-admin using systemd and gunicorn, so that it binds to a unix socket.  This is the proxy socket mentioned in the nginx config.
* Make sure to run `systemctl daemon-reload` and `systemd-tmpfiles --create` after setting up the config

This setup appears to work for us.  Note that I've installed under /opt/powerdns-admin , and that this config is for release 0.2.1 with  the config in powerdnsadmin/config.py

/etc/nginx/conf.d/powerdns-admin.conf
```
server {
  listen *:80;
  server_name         _;

  index                     index.html index.htm index.php;
  root                      /opt/powerdns-admin;
  access_log                /var/log/nginx/powerdns-admin.local.access.log combined;
  error_log                 /var/log/nginx/powerdns-admin.local.error.log;

  client_max_body_size              10m;
  client_body_buffer_size           128k;
  proxy_redirect                    off;
  proxy_connect_timeout             90;
  proxy_send_timeout                90;
  proxy_read_timeout                90;
  proxy_buffers                     32 4k;
  proxy_buffer_size                 8k;
  proxy_set_header                  Host $host;
  proxy_set_header                  X-Real-IP $remote_addr;
  proxy_set_header                  X-Forwarded-For $proxy_add_x_forwarded_for;
  proxy_headers_hash_bucket_size    64;

  location ~ ^/static/  {
    include  /etc/nginx/mime.types;
    root /opt/powerdns-admin/powerdnsadmin;

    location ~*  \.(jpg|jpeg|png|gif)$ {
      expires 365d;
    }

    location ~* ^.+.(css|js)$ {
      expires 7d;
    }
  }

  location / {
    proxy_pass            http://unix:/run/powerdns-admin/socket;
    proxy_read_timeout    120;
    proxy_connect_timeout 120;
    proxy_redirect        off;
  }

}
```

/etc/systemd/system/powerdns-admin.service
```
[Unit]
Description=PowerDNS web administration service
Requires=powerdns-admin.socket
Wants=network.target
After=network.target mysqld.service postgresql.service slapd.service mariadb.service

[Service]
PIDFile=/run/powerdns-admin/pid
User=pdnsa
Group=pdnsa
WorkingDirectory=/opt/powerdns-admin
ExecStart=/usr/bin/gunicorn-3.6 --workers 4 --log-level info --pid /run/powerdns-admin/pid --bind unix:/run/powerdns-admin/socket "powerdnsadmin:create_app(config='config.py')"
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true
Restart=on-failure
RestartSec=10
StartLimitInterval=0

[Install]
WantedBy=multi-user.target
```
powerdns-admin.socket
```
[Unit]
Description=PowerDNS-Admin socket

[Socket]
ListenStream=/run/powerdns-admin/socket

[Install]
WantedBy=sockets.target
```

/etc/tmpfiles.d/powerdns-admin.conf
```
d /run/powerdns-admin 0755 pdnsa pdnsa -
```

**Comment by sshipway** [comment]
The TLDR for above is - you're possibly running your server on port localhost:9191 but you want it to be on unix:/run/powerdns-admin/socket instead so that nginx or apache can proxy to it.  Else, change the proxy_pass definition in the nginx config.
