### ISSUE TITLE
Unable to register new user: "NoneType object has no attribute id"

### ISSUE THREAD

**Issue by sshipway** [PowerDNS-Admin/PowerDNS-Admin#627]
This looks like a regression of an error from a previous version ( #319 #194 maybe ) 

Fresh install of version 0.2.1 under CentOS 7.  Python 3.6, gunicorn, systemd, postgresdb

When trying to register first user, all correct data are entered, but it fails to work and gives the red error message:
`'NoneType' object has no attribute 'id' `

No errors are logged in the logfile to indicate the cause.

**Comment by sshipway** [comment]
This appears to be because the database has an empty "Role" table, and the creation of the first account assumes that the Administrator role will already exist.  
There does not appear to be any installation instructions or tool to create the initial data?  Even information that you need to run 'flask db migrate' to initialise the tables is missing form the Postgres instructions, and this fails because it always uses "default_config.py" for its configuration rather than config.py

* The "flask db" utility should use config.py if available
* The install instructions should mention clearly how to initialise the database
* The database initialisation should include creating the required basic records (roles, templates etc) as in previous versions
* The initial user creation should not fail if there are no Administrator, Operator and User roles defined; instead these should be automatically created by the system
* A failed user creation should log a more detailed trace to the logfile to help with debugging

**Comment by ngoduykhanh** [comment]
You faced those issues because the database wasn't initialized properly.
The new version of PDA keeps the same migration scripts as the previous one so the basic records (roles, templates) will be created.

Before running `flask db upgrade`, we need to set the following environment variables:

- FLASK_APP=powerdnsadmin/__init__.py
- FLASK_CONF=<your-config-file>

If you don't set the `FLASK_CONF` variable, it will use the default_config.py file.

Btw, I am going to add more docs in the repo to keep it up-to-date. The docs in the WIKI page contributed by several users so it might be outdated.

**Comment by sshipway** [comment]
I have been trying to create a .repo file for building an RPM of PowerDNS-Admin, so that it can be installed automatically by our system here.  Unfortunately the use of Flask, Pip, and nodejs has made it rather difficult - not to mention trying to find some way to automate database initialisation post-install.  Currently, the 'flask assets build' is the main part causing me issues as for some reason the 'assets' command is not recognised when flask is run within rpmbuild.

**Comment by jbe-dw** [comment]
Hello,

Can we close this issue ? What is the status about building RPMs ?

Regards
