### ISSUE TITLE
OIDC Account mapping

### ISSUE THREAD

**Issue by eriweb** [PowerDNS-Admin/PowerDNS-Admin#718]
I have been pondering about a way to automatically create accounts (not user accounts, but accounts) and I came up with this idea. Before I start developing it I would like some feedback.

Add settings for account name, and account description. Given that these have different syntax I'm also thinking of adding a field where the admin can supply a regexp to use (ie. account name regexp, account description regexp). 

This is to support claim names that may have to wrap and separate those values by some separator.

Do a search for the account, if it exists, check if user is member, if not add it. Also check that account description matches, if not, update.

If account does not exists, create it and add user.

Does this sound viable? And is it something you would accept upstream assuming the code conforms to standards?

**Comment by maximumG** [comment]
I was thinking about the same concept regarding PowerDNS Admin account mapping with OIDC claim. We would like to delegate administration to our customers on their respective DNS zones. Each customer would have several users that may connect to powerdns-admin interface. All of our customer are using our SSO portal for authentication (keycloak).

I didn't understand which OIDC claim you would use in order to store the account name  ?

On my side we are using Keycloak as OIDC provider and I was thinking about using a custom claim named `company` which will hold the account name of the user (hence the company name). So I was thinking of an additionnal Setting in OIDC in order to instruct powerdns-admin in which claim to search for the account.

I was hoping that this could be accepted too 😄

**Comment by terbolous** [comment]
After some more thoughts I realized that for my use case I want the user to possibly be part of several accounts. We're using Azure AD and the only claim I found that allow for such is `group`. So I ended up making a PoC for Azure AD (with the Microsoft Authentication in PowerDNS-Admin). It should be ready for review quite soon, and I believe most of it can be reused in the regular OIDC Authenticator

**Comment by sshipway** [comment]
Probably, the best way to do it would be to allow groups to be allocated to accounts.
Currently, the Azure OICD allows groups to be mapped to Admin, Operator, User roles.  It might be possible to allow creation of custom Roles, and map other groups to these; then to grant Roles access to Accounts rather than just individuals?

**Comment by terbolous** [comment]
I have implemented groups -> accounts mapping and plan to finish a PR with it. It's Azure specific since it uses the graph api to fetch groups, but it shouldn't be overly hard to replace those part with something more OIDC generic for those who want it

**Comment by jbe-dw** [comment]
Related #740

**Comment by jbe-dw** [comment]
Hello,

The OIDC account provisioning has been implemented.

Regards
