### ISSUE TITLE
Breaks the domain when adding entries in bulk

### ISSUE THREAD

**Issue by serafim101** [PowerDNS-Admin/PowerDNS-Admin#744]
When you try to add multiple A records, on one FQDN, of one transaction, it starts randomly deleting records from the domain database, including A, NS, SNAME, etc.
If you add one A record per transaction, then everything is applied normally. But adding one record at a time, when you need to add about 100 records, is extremely inconvenient.

**Comment by ngoduykhanh** [comment]
Can you show the steps with examples to reproduce this bug? As I understand, you cannot add multiple A records at the same time. However, It looks good on my test.

**Comment by serafim101** [comment]
This problem is observed when adding new A records, provided that the record to which we are adding is already in the database.
For instance:
I have these A records:
host.example.com IN A 10.0.0.1
host.example.com IN A 10.0.0.2
host.example.com IN A 10.0.0.2
I want to add a new entry:
host.example.com IN A 10.0.0.100
After clicking apply, all entries
host.example.com IN A 10.0.0.1
host.example.com IN A 10.0.0.2
host.example.com IN A 10.0.0.2
Completely disappear.
As I understand it, this happens because the PATCH method is used to access the pdns api when I need to add something to an existing domain.
Is it possible to implement the method of adding with a preliminary check for the presence of such an entry in the database, and if such an entry exists, then parse them and automatically add them to the pdns request so as not to lose the existing entries?
And if you use the update function, or replace the record, then so that it does everything as before, i.e. completely replaced the old record in the database with a new one?

**Comment by ngoduykhanh** [comment]
> host.example.com IN A 10.0.0.1
> host.example.com IN A 10.0.0.2
> host.example.com IN A 10.0.0.2

Just want to clarify, your 3rd record IP should be `10.0.0.3` right?
I tried with your sample, and it does work for me. No record got deleted.
Can you show the "recent history detail" after you apply? It would show more information.

Regarding the PATCH method, it is required by the PDNS API. You can see the docs [here](https://doc.powerdns.com/authoritative/http-api/zone.html#patch--servers-server_id-zones-zone_id)

**Comment by serafim101** [comment]
> Just want to clarify, your 3rd record IP should be `10.0.0.3` right?

Yes. Absolutely right

**Comment by serafim101** [comment]
> Can you show the "recent history detail" after you apply? It would show more information.

Unfortunately no. This information is already lost.

**Comment by serafim101** [comment]
For instance:
I have these A records:
host.example.com IN A 10.0.0.1
host.example.com IN A 10.0.0.2
host.example.com IN A 10.0.0.3
I want to add a new entry:
host.example.com IN A 10.0.0.100
After clicking apply, all entries
host.example.com IN A 10.0.0.1
host.example.com IN A 10.0.0.2
host.example.com IN A 10.0.0.3
Completely disappear.
--------------------------------------------
There is one feature in this example that I forgot to mention at the beginning. All NS records are also deleted from the domain in which we added records, only one NS record remains, instead of 8

**Comment by pprietosanchez** [comment]
Hello,

I'm in the same issue, as I can know without further investigation (I'm on it), when you add multiple new records, randomly, add to the rrsets deletions, on my case, the MX records and many more (A records, NS, including subdomains)

The issue is harder when you try to add a duplicate record (for example, add an A record with same name and IP that one existing yet), because the powerdns.admin show an error, and no log on history nothing, but, the first operation that the app does is delete the record, and then tries to create with the same IP twice, and the pdns API trows an error, and the result is that the first record is deleted, and no info on the history about it.

Best regards!

**Comment by pprietosanchez** [comment]
I have some news about my last comment, I don't know that is the same issue, I think yes, is not only when you add bulk records, the issue is reproducible when you add one or more records, then apply changes and then add more records and apply again.

More schematic:
Go to "Manage domain"
Add record
apply changes
add record
apply changes

This second "apply changes" do more operations that was made by the user on the interface.

@ngoduykhanh , do you want to add a new issue with this specific case?

Thank you

**Comment by ngoduykhanh** [comment]
> More schematic:
Go to "Manage domain"
Add record
apply changes
add record
apply changes

@pprietosanchez I don't get it. What is the problem with this procedure? I only see the issue you mentioned in #752

**Comment by pprietosanchez** [comment]
@ngoduykhanh is another issue than #752 , in this case the issue occurs when you follow the steps described on https://github.com/ngoduykhanh/PowerDNS-Admin/issues/744#issuecomment-639308554

The relationship involved two issues is when both occurs at the same time, in an schematic example:

1 Go to "Manage domain"
2 Add record
3 apply changes
4 add duplicate record (reproducing #752 )
5 apply changes

If these steps occcurs, the result of this is the lost of arbitrary records on domain, including NS, MX, etc....

I hope I've been clear enough

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
