### ISSUE TITLE
Can't add LOC records

### ISSUE THREAD

**Issue by Gougere89** [PowerDNS-Admin/PowerDNS-Admin#799]
Hello, 

I have a problem with PowerDNS-admin

When I try to add a LOC record (for example, at the root of my domain), when applying changes it returns an error. 

I tried with different LOC values. 
For example, that one : `47 10 39.655 N 3 59 39.308 E 593m 10m 100m 10m` (I picked a random place)
i tried both with and without quotes surrounding the data; 
Without quotes, I get that error: 

```
Record mydomain.net./LOC 47 10 39.655 N 3 59 39.308 E 593m 10m 100m 10m: Not in expected format (parsed as 47 10 39.655 N 3 59 39.308 E 593.00m 10.00m 100.00m 10.00m)
```

And with quotes I get that one:

```
Record mydomain.net./LOC "47 10 39.655 N 3 59 39.308 E 593m 10m 100m 10m": Error decoding LOC content
```

Thank you. 
Oh, and I am sorry for my english ^^'

**Comment by bryanpedini** [comment]
I don't remember which parameter does what, in which order, and what makes what. But I can provide you a working example: `49 24 50.436 N 11 10 15.812 E 15.00m 50.00m 10.00m 10.00m` (directly from PowerDNS-Admin interface).
I'm with Contabo as provider, so that is their Nuremberg data center. It does correctly resolve with `dig LOC bjphoster.com`.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. Feel free to open a new issue later if you still encounter this problem.

Regards
PowerDNS Admin Team
See #1153 for the policy
