### ISSUE TITLE
[BUG] API basic authentication fails if password contains ':'

### ISSUE THREAD

**Issue by itbane** [PowerDNS-Admin/PowerDNS-Admin#849]
Hi,

the basic auth of the API fails if the user's password contains a colon (':').

**Steps to reproduce:**
- Install a new pdnsadmin instance (e.g. docker)
- Create the initial user with a password that contains ':'
- try using the '/accounts' API with Basic auth using the base64 encoded user:password string

**Observed Behaviour**
- Response Code: 401 Unauthorized
- Error in PDNS-Admin Log:
[stacktrace-colonpassword.txt](https://github.com/ngoduykhanh/PowerDNS-Admin/files/5707675/stacktrace-colonpassword.txt)

**expected behaviaour**
- get a list of accounts - empty for a new installation

KR

**Comment by jbe-dw** [comment]
This is because colon is the field separator for the basic auth. The message says that it lookup for two elements but more were given (three if you have a colon in your password).

It can be easily patched though I wouldn't be sure there would not be extra issues:

* Forbidding colon on password validation
* Patching [this line](https://github.com/ngoduykhanh/PowerDNS-Admin/blob/2917c47fd1c78194d3462687b3a31c17c42e308e/powerdnsadmin/decorators.py#L109)

```
authentication = auth_header.split(":")
username, password = authentication[0], ':'.join(authentifcation[1::])
```
Don't forget to restart gunicorn or any cgi processor.

If this quick fix doesn't work then consider avoiding this character because the fix may be proposed in quite some time.
