### ISSUE TITLE
Feature Request: Ability to configure natively PDA under a subdirectory

### ISSUE THREAD

**Issue by corporategoth** [PowerDNS-Admin/PowerDNS-Admin#866]
I'm trying to use this application via. a proxy:

So instead of having to expose http://xyz:9191/, I can go to http://xyz/powerdns

I have an nginx config like this:

```
    location /powerdns/ {
        sub_filter '"/static/'  '"/powerdns/static/';
        sub_filter '"/dashboard/'  '"/powerdns/dashboard/';
        sub_filter "'/domain/"  "'/powerdns/domain/";
        sub_filter "'/admin/"  "'/powerdns/admin/";
        sub_filter "'/logout"  "'/powerdns/logout";
        sub_filter "'/ping"  "'/powerdns/ping";
        sub_filter 'href="/admin/'  'href="/powerdns/admin/';
        sub_filter 'href="/user/'  'href="/powerdns/user/';
        sub_filter 'href="/logout'  'href="/powerdns/logout';
        sub_filter_once off;
        sub_filter_types application/javascript;
        proxy_pass http://powerdns-admin/;
    }

    location /domain/ {
        return 301 $scheme://$host/powerdns$request_uri;
    }
```

It ALMOST works .. but not quite - no matter what I do I can't get a subfilter to fix  the /domain/example.com urls (so I have to use a redirect above).

But the bigger problem is, there is no way to set the site_url variable.  It's hard coded to http://localhost:9191

If the site_url could be configured, I would not need ANY of the sub_filters - I could just set it to http://xyz/powerdns

Please allow the SITE_URL to be configured so that I don't have to try and do these kind of gymnastics just to properly proxy the application.

**Comment by corporategoth** [comment]
Hrm, looks like this was already requested .. and ignored ... a year ago - https://github.com/ngoduykhanh/PowerDNS-Admin/issues/638

**Comment by aeular** [comment]
I just went through this as well with the docker, but gave in and made nginx deal with it.  After your proxy_pass line, I added 2 lines (tweaked to your config, as I just devote a sub domain instead):
proxy_redirect https://127.0.0.1:9191/ /powerdns/;
proxy_redirect http://127.0.0.1:9191/ /powerdns/;

Those make it rewrite the location header, in this case removing the https://127.0.0.1:9191/ or http://127.0.0.1:9191/ to make the redirect not specify the domain or port.  If you want to do full redirects, you could do something like these two:

proxy_redirect http://127.0.0.1:9191/ $scheme://$host:$server_port/powerdns/;
proxy_redirect https://127.0.0.1:9191/ $scheme://$host:$server_port/powerdns/;

And I agree it's sub-optimal that we need to do this via nginx instead of being able to configure it.

**Comment by jbe-dw** [comment]
Hello,

This request is stale for too long. Regarding our policy to cleanup this project, we are closing it. As this is a Feature Request, it will be listed in #1178

Regards
PowerDNS Admin Team
See #1153 for the policy

**Comment by IamIpanda** [comment]
Just a mention here if you don't want to use proxy redirect that lock your domain, you can give up the `/domain` subdir and assign it to powerdns:

```
location /domain/ {
    rewrite ^/(.*) $scheme://$host:$server_port/powerdns/$1 redirect;
}
```
That can just work.
