### ISSUE TITLE
PTR (Reverse DNS) is not Resolving Locally.

### ISSUE THREAD

**Issue by MoizEzzy** [PowerDNS-Admin/PowerDNS-Admin#875]
Hello,

I have Followed Blog For Configuring Power DNS + Power DNS Admin.

https://www.howtoforge.com/how-to-install-powerdns-admin-on-ubuntu-20-04/

After setting up all the things I have created RDNS From Admin Panel, But it is not resolving, Please Refer Below Attachments.

Please Let me know if You Require anything Else.

![Screenshot 2021-01-27 154700](https://user-images.githubusercontent.com/63609792/105977129-068b3480-60b7-11eb-8bf3-d99aed31f19e.jpg)
![Screenshot 2021-01-27 154712](https://user-images.githubusercontent.com/63609792/105977142-0854f800-60b7-11eb-9afc-e91f9a69fd6a.jpg)
![Screenshot 2021-01-27 154730](https://user-images.githubusercontent.com/63609792/105977153-0b4fe880-60b7-11eb-8740-0285bea7fa39.jpg)

**Comment by larslehmann-net** [comment]
Hello,

you must only enter the last part of the IP to the RTP Record.
In your Example you must set the RTP Records with the Names 4 and 10, because the rest is already set over the Zone.

![Screenshot_1](https://user-images.githubusercontent.com/33843261/105996152-3ed84600-60aa-11eb-896e-111d01892e0d.png)
![Screenshot_2](https://user-images.githubusercontent.com/33843261/105996153-3f70dc80-60aa-11eb-8bc9-1384e3e9e7d1.png)

**Comment by MoizEzzy** [comment]
Hello,

Thats Great it Worked It is Resolving Locally, But i am not Sure Why i am not able to ping google.com From My Server.
![Screenshot 2021-01-28 140050](https://user-images.githubusercontent.com/63609792/106110854-444c9380-6171-11eb-99e4-8b05f0b1982f.jpg)

**Comment by larslehmann-net** [comment]
Hello,

PowerDNS consists of several components once the **PowerDNS Authoritative Server** that you have set up, which is only there to resolve its own zones (test.com).
The **PowerDNS Recursor** is a resolver that searches for the authority DNS server of the searched zone (google.com) based on the Root DNS and TLD DNS servers and then asks the Authority Server (ns1.google.com) for the record.

The different types are also described quite well here. https://www.cloudflare.com/learning/dns/dns-server-types/

So, in order to resolve external zones (google.com), you would also need the Recursor, which then forwards the requests to the local zone (test.com) to your Authoritative Server.

**Comment by MoizEzzy** [comment]
Hello,

I Didn't Got that DNS Stuff but it seems like My Domain name or hostname should be resolved globally but not local only.
but so why i am able to ping 8.8.8.8 and not google.com i have public ip for my server & when i add 8.8.8.8 in /etc/resolv.conf google.com start pinging but nslookup stoped working for my local addr domain.
Please guide.

![Screenshot 2021-01-28 185709](https://user-images.githubusercontent.com/63609792/106144750-a4a3fb00-619a-11eb-9e28-da7b39400849.jpg)

**Comment by jbe-dw** [comment]
Hello,
I don't exactly undertand your question but I'll complete @larslehmann-net  answer to be clear. There are two kinds of DNS Servers:

- Authoritative : These servers literally hosts zones content. What you installed is PowerDNS Authoritative Server. PowerDNS Admin is the frontend to manage PowerDNS Authoritative Server content.
- Recursive: These servers take all the clients requests and try to resolve it recursively to answer the requests. This is done by PowerDNS Recursor, which is another software.

When you configure a client, it should be configured to reach a Recursive Server :

- the recursive server will resolve any request for your client (google.com, github.com ...)
- it will instead not be able to resolve your local domains if they are not registered in a registrar and behaving correctly with a public IP (the recursion chain must be set correctly) **UNLESS** you locally add a FORWARD directive to your Recursive server to point at the local IP of your Authoritative server for all the zones you are hosting. As private IP ranges reverse domain are not served over public DNS, **the FORWARD is a requirement for private ip subnet reverse domains**.

Pointing your client to your Authoritative server will fail for any domain not served by your server. You have to install a recursor and configure your client to send requests to the recursor instead. Then, if your domain is not available outside your organization, you have to configure a zone forward inside your recursor to point the required domains to your internal Authoritative server.

I hope it's a bit more clear for you.
