### ISSUE TITLE
500 Oops! Something went wrong

### ISSUE THREAD

**Issue by gregrwm** [PowerDNS-Admin/PowerDNS-Admin#908]
there's one domainname in our database, when we click on that domainname on the dashboard, it just says "500 Oops! Something went wrong".

there's probably a log somewhere i can go look at?  buried in the docker container no doubt?  how do i go find it?

**Comment by gregrwm** [comment]
whenever we try to click that domainname on the dashboard, this gets logged in /var/log/syslog:
`Mar 16 19:29:27 g152 pdns_server[86193]: [webserver] 949e61c8-4a23-43d9-8325-f18e0e1e69fb HTTP ISE for "/api/v1/servers/localhost/zones/prospectparkmpls.org": STL Exception: Parsing record content (try 'pdnsutil check-zone'): Data field in DNS should start with quote (") at position 0 of 'google-site-verification=TL_Bn4yImxu1M3VMOdmXBCN29qExL7A-N4pP1FL8FWU'`

**Comment by gregrwm** [comment]
it appears the problem is content in TXT records that's not quoted.  those text records are just as they were imported (from bind/named files).  most such TXT records were quoted, but that one wasn't.

**Comment by gregrwm** [comment]
i added quotes, and it's fine now.

this issue might be of interest if powerdns-admin wants to put any effort toward being more graceful about it.

but of course i need to say thanks much for how well powerdns-admin works already...

**Comment by 7c** [comment]
same problem, we have changed from old powerdns UI to this one but some of our domains do 500 because of quotation inside TXT records;
success:
`INSERT INTO `records` (`id`, `domain_id`, `name`, `type`, `content`, `ttl`, `prio`, `change_date`, `disabled`, `ordername`, `auth`) VALUES
(NULL, 935, 'test2.testing2.com', 'TXT', '"zoho-verification=zb74249764.zmverify.zoho.com"', 86400, 0, NULL, 0, NULL, 1)
`
fails:
`INSERT INTO `records` (`id`, `domain_id`, `name`, `type`, `content`, `ttl`, `prio`, `change_date`, `disabled`, `ordername`, `auth`) VALUES
(NULL, 935, 'test2.testing2.com', 'TXT', 'zoho-verification=zb74249764.zmverify.zoho.com', 86400, 0, NULL, 0, NULL, 1)`


I have checked powerdns latest version, also previous versions:

```
test.testing2.com descriptive text "zoho-verification=zb74249764.zmverify.zoho.com"
test2.testing2.com descriptive text "zoho-verification=zb74249764.zmverify.zoho.com"
```

they do just fine. I believe PowerDNS needs to mitigate this issue, I understand that the proper way might be with quotes but we should not try to beat powerdns which is the only reason for this wonderful product.

**Comment by jbe-dw** [comment]
Hello,

We are doing some cleanup, i'll get a look at this later.

Regards

**Comment by jbe-dw** [comment]
Hello,

Looking at this issues it happens that the error is from PowerDNS database itself. PowerDNS Admin has functions that check on TXT format in the UI. It then transmits to the PowerDNS API who declines the update if the record format does not comply.

If you think that the check in the UI are not sufficient, please open a new issue.

Regards
