### ISSUE TITLE
Account data: reference precedence in pdnsadmin domain records vs. pdns domain records

### ISSUE THREAD

**Issue by usrflo** [PowerDNS-Admin/PowerDNS-Admin#958]
I propose to change the sync of account information from the pdns.domains data-table back to powerdns on user logins, see existing implementation at https://github.com/ngoduykhanh/PowerDNS-Admin/blob/b66b37ecfdc512449e7b6519f3b9f1619de343a2/powerdnsadmin/models/domain.py#L145 and the linkage insight at https://github.com/ngoduykhanh/PowerDNS-Admin/issues/584

In case a domain record already exists in the pdnsadmin database the account_id IMHO should not be changed (including no reset to NULL if pdns.domains.account is NULL). In my view powerdns is the leading system regarding account information. Maybe a pdnsadmin config value can be introduced to control this behavior of account data precedence (?)

**Comment by jbe-dw** [comment]
Hello,

Since PDA does not store records in its DB, this is not even possible. We already discovered that records account information is deleted by PDA and we will provide a fix to, at least, not erase the information when submitting records. It only manages the domains <> account association.

We don't plan to manage record's account association in PDA in near future.

Regards
